---
include:
  # - board: nice_nano//zmk
    # shield: bav_left
  # - board: nice_nano//zmk
    # shield: bav_right
  - board: nice_nano//zmk
    shield: keebagn_right
  - board: nice_nano//zmk
    shield: keebagn_left
  # - board: nice_nano//zmk
  #   shield: settings_reset
  # - board: nice_nano//zmk
  #   shield: tester_pro_micro
